
export const enum Speciality {
    UROLOGY = "Urology",
    ONCOLOGY = "Oncology",
    NEUROLOGY = "Neurology",
    RADIOLOGY = "Radiology",
    PSYCHIATRY = "Psychiatry",
    CARDIOLOGY = "Cardiology",
    PEDIATRICS = "Pediatrics",
    DERMATOLOGY = "Dermatology",
    ORTHOPEDICS = "Orthopedics",
    PULMONOLOGY = "Pulmonology",
    RHEUMATOLOGY = "Rheumatology",
    ENDOCRINOLOGY = "Endocrinology",
    OPHTHALMOLOGY = "Ophthalmology",
    ANESTHESIOLOGY = "Anesthesiology",
    SURGERY_GENERAL = "General Surgery",
    FAMILY_MEDICINE = "Family Medicine",
    GASTROENTEROLOGY = "Gastroenterology",
    INTERNAL_MEDICINE = "Internal Medicine",
    EMERGENCY_MEDICINE = "Emergency Medicine",
    OBSTETRICS_GYNECOLOGY = "Obstetrics & Gynecology",
}

export const Specialities: Speciality[] = [
    Speciality.UROLOGY,
    Speciality.ONCOLOGY,
    Speciality.NEUROLOGY,
    Speciality.RADIOLOGY,
    Speciality.PSYCHIATRY,
    Speciality.CARDIOLOGY,
    Speciality.PEDIATRICS,
    Speciality.DERMATOLOGY,
    Speciality.ORTHOPEDICS,
    Speciality.PULMONOLOGY,
    Speciality.RHEUMATOLOGY,
    Speciality.ENDOCRINOLOGY,
    Speciality.OPHTHALMOLOGY,
    Speciality.ANESTHESIOLOGY,
    Speciality.SURGERY_GENERAL,
    Speciality.FAMILY_MEDICINE,
    Speciality.GASTROENTEROLOGY,
    Speciality.INTERNAL_MEDICINE,
    Speciality.EMERGENCY_MEDICINE,
    Speciality.OBSTETRICS_GYNECOLOGY,
]
